linked_adjacency_graph: main.o 
	g++ main.o -o linked_adjacency_graph
main.o: main.cpp adjacencyListGraph.h arrayQueue.h linkedList.h node.h vertex.h
	g++ -c main.cpp
clean:
	rm *.o linked_adjacency_graph